// Generated by gencpp from file object_tracking/SetTarget.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKING_MESSAGE_SETTARGET_H
#define OBJECT_TRACKING_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <object_tracking/SetTargetRequest.h>
#include <object_tracking/SetTargetResponse.h>


namespace object_tracking
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace object_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_tracking::SetTarget > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::object_tracking::SetTarget&) { return value(); }
};

template<>
struct DataType< ::object_tracking::SetTarget > {
  static const char* value()
  {
    return "object_tracking/SetTarget";
  }

  static const char* value(const ::object_tracking::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::object_tracking::SetTargetRequest> should match
// service_traits::MD5Sum< ::object_tracking::SetTarget >
template<>
struct MD5Sum< ::object_tracking::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracking::SetTarget >::value();
  }
  static const char* value(const ::object_tracking::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracking::SetTargetRequest> should match
// service_traits::DataType< ::object_tracking::SetTarget >
template<>
struct DataType< ::object_tracking::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::object_tracking::SetTarget >::value();
  }
  static const char* value(const ::object_tracking::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_tracking::SetTargetResponse> should match
// service_traits::MD5Sum< ::object_tracking::SetTarget >
template<>
struct MD5Sum< ::object_tracking::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracking::SetTarget >::value();
  }
  static const char* value(const ::object_tracking::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracking::SetTargetResponse> should match
// service_traits::DataType< ::object_tracking::SetTarget >
template<>
struct DataType< ::object_tracking::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::object_tracking::SetTarget >::value();
  }
  static const char* value(const ::object_tracking::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_TRACKING_MESSAGE_SETTARGET_H
