(cl:defpackage lab_config-srv
  (:use )
  (:export
   "CHANGERANGE"
   "<CHANGERANGE-REQUEST>"
   "CHANGERANGE-REQUEST"
   "<CHANGERANGE-RESPONSE>"
   "CHANGERANGE-RESPONSE"
   "GETALLCOLORNAME"
   "<GETALLCOLORNAME-REQUEST>"
   "GETALLCOLORNAME-REQUEST"
   "<GETALLCOLORNAME-RESPONSE>"
   "GETALLCOLORNAME-RESPONSE"
   "GETRANGE"
   "<GETRANGE-REQUEST>"
   "GETRANGE-REQUEST"
   "<GETRANGE-RESPONSE>"
   "GETRANGE-RESPONSE"
   "STASHRANGE"
   "<STASHRANGE-REQUEST>"
   "STASHRANGE-REQUEST"
   "<STASHRANGE-RESPONSE>"
   "STASHRANGE-RESPONSE"
  ))

