// Generated by gencpp from file lab_config/ChangeRangeRequest.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_CHANGERANGEREQUEST_H
#define LAB_CONFIG_MESSAGE_CHANGERANGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_config
{
template <class ContainerAllocator>
struct ChangeRangeRequest_
{
  typedef ChangeRangeRequest_<ContainerAllocator> Type;

  ChangeRangeRequest_()
    : min()
    , max()  {
    }
  ChangeRangeRequest_(const ContainerAllocator& _alloc)
    : min(_alloc)
    , max(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _min_type;
  _min_type min;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::lab_config::ChangeRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_config::ChangeRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeRangeRequest_

typedef ::lab_config::ChangeRangeRequest_<std::allocator<void> > ChangeRangeRequest;

typedef boost::shared_ptr< ::lab_config::ChangeRangeRequest > ChangeRangeRequestPtr;
typedef boost::shared_ptr< ::lab_config::ChangeRangeRequest const> ChangeRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_config::ChangeRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_config::ChangeRangeRequest_<ContainerAllocator1> & lhs, const ::lab_config::ChangeRangeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_config::ChangeRangeRequest_<ContainerAllocator1> & lhs, const ::lab_config::ChangeRangeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_config::ChangeRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::ChangeRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::ChangeRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f3b135930968ee1e0f8c35f66cb9493";
  }

  static const char* value(const ::lab_config::ChangeRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f3b135930968ee1ULL;
  static const uint64_t static_value2 = 0xe0f8c35f66cb9493ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_config/ChangeRangeRequest";
  }

  static const char* value(const ::lab_config::ChangeRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] min\n"
"int16[] max\n"
;
  }

  static const char* value(const ::lab_config::ChangeRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_config::ChangeRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_config::ChangeRangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "min[]" << std::endl;
    for (size_t i = 0; i < v.min.size(); ++i)
    {
      s << indent << "  min[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.min[i]);
    }
    s << indent << "max[]" << std::endl;
    for (size_t i = 0; i < v.max.size(); ++i)
    {
      s << indent << "  max[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.max[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_CHANGERANGEREQUEST_H
