// Generated by gencpp from file lab_config/GetAllColorNameResponse.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_GETALLCOLORNAMERESPONSE_H
#define LAB_CONFIG_MESSAGE_GETALLCOLORNAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_config
{
template <class ContainerAllocator>
struct GetAllColorNameResponse_
{
  typedef GetAllColorNameResponse_<ContainerAllocator> Type;

  GetAllColorNameResponse_()
    : color_names()  {
    }
  GetAllColorNameResponse_(const ContainerAllocator& _alloc)
    : color_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _color_names_type;
  _color_names_type color_names;





  typedef boost::shared_ptr< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAllColorNameResponse_

typedef ::lab_config::GetAllColorNameResponse_<std::allocator<void> > GetAllColorNameResponse;

typedef boost::shared_ptr< ::lab_config::GetAllColorNameResponse > GetAllColorNameResponsePtr;
typedef boost::shared_ptr< ::lab_config::GetAllColorNameResponse const> GetAllColorNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_config::GetAllColorNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_config::GetAllColorNameResponse_<ContainerAllocator1> & lhs, const ::lab_config::GetAllColorNameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.color_names == rhs.color_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_config::GetAllColorNameResponse_<ContainerAllocator1> & lhs, const ::lab_config::GetAllColorNameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07eeaa0f3311bac2cbbe7fd861374c5c";
  }

  static const char* value(const ::lab_config::GetAllColorNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07eeaa0f3311bac2ULL;
  static const uint64_t static_value2 = 0xcbbe7fd861374c5cULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_config/GetAllColorNameResponse";
  }

  static const char* value(const ::lab_config::GetAllColorNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] color_names\n"
;
  }

  static const char* value(const ::lab_config::GetAllColorNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAllColorNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_config::GetAllColorNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_config::GetAllColorNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "color_names[]" << std::endl;
    for (size_t i = 0; i < v.color_names.size(); ++i)
    {
      s << indent << "  color_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_GETALLCOLORNAMERESPONSE_H
