// Generated by gencpp from file lab_config/GetAllColorName.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_GETALLCOLORNAME_H
#define LAB_CONFIG_MESSAGE_GETALLCOLORNAME_H

#include <ros/service_traits.h>


#include <lab_config/GetAllColorNameRequest.h>
#include <lab_config/GetAllColorNameResponse.h>


namespace lab_config
{

struct GetAllColorName
{

typedef GetAllColorNameRequest Request;
typedef GetAllColorNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAllColorName
} // namespace lab_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab_config::GetAllColorName > {
  static const char* value()
  {
    return "07eeaa0f3311bac2cbbe7fd861374c5c";
  }

  static const char* value(const ::lab_config::GetAllColorName&) { return value(); }
};

template<>
struct DataType< ::lab_config::GetAllColorName > {
  static const char* value()
  {
    return "lab_config/GetAllColorName";
  }

  static const char* value(const ::lab_config::GetAllColorName&) { return value(); }
};


// service_traits::MD5Sum< ::lab_config::GetAllColorNameRequest> should match
// service_traits::MD5Sum< ::lab_config::GetAllColorName >
template<>
struct MD5Sum< ::lab_config::GetAllColorNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::GetAllColorName >::value();
  }
  static const char* value(const ::lab_config::GetAllColorNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::GetAllColorNameRequest> should match
// service_traits::DataType< ::lab_config::GetAllColorName >
template<>
struct DataType< ::lab_config::GetAllColorNameRequest>
{
  static const char* value()
  {
    return DataType< ::lab_config::GetAllColorName >::value();
  }
  static const char* value(const ::lab_config::GetAllColorNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab_config::GetAllColorNameResponse> should match
// service_traits::MD5Sum< ::lab_config::GetAllColorName >
template<>
struct MD5Sum< ::lab_config::GetAllColorNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::GetAllColorName >::value();
  }
  static const char* value(const ::lab_config::GetAllColorNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::GetAllColorNameResponse> should match
// service_traits::DataType< ::lab_config::GetAllColorName >
template<>
struct DataType< ::lab_config::GetAllColorNameResponse>
{
  static const char* value()
  {
    return DataType< ::lab_config::GetAllColorName >::value();
  }
  static const char* value(const ::lab_config::GetAllColorNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_GETALLCOLORNAME_H
