// Generated by gencpp from file lab_config/GetRange.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_GETRANGE_H
#define LAB_CONFIG_MESSAGE_GETRANGE_H

#include <ros/service_traits.h>


#include <lab_config/GetRangeRequest.h>
#include <lab_config/GetRangeResponse.h>


namespace lab_config
{

struct GetRange
{

typedef GetRangeRequest Request;
typedef GetRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRange
} // namespace lab_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab_config::GetRange > {
  static const char* value()
  {
    return "c7b2c33b1c9c860ea4b8bdc266a1aed8";
  }

  static const char* value(const ::lab_config::GetRange&) { return value(); }
};

template<>
struct DataType< ::lab_config::GetRange > {
  static const char* value()
  {
    return "lab_config/GetRange";
  }

  static const char* value(const ::lab_config::GetRange&) { return value(); }
};


// service_traits::MD5Sum< ::lab_config::GetRangeRequest> should match
// service_traits::MD5Sum< ::lab_config::GetRange >
template<>
struct MD5Sum< ::lab_config::GetRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::GetRange >::value();
  }
  static const char* value(const ::lab_config::GetRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::GetRangeRequest> should match
// service_traits::DataType< ::lab_config::GetRange >
template<>
struct DataType< ::lab_config::GetRangeRequest>
{
  static const char* value()
  {
    return DataType< ::lab_config::GetRange >::value();
  }
  static const char* value(const ::lab_config::GetRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab_config::GetRangeResponse> should match
// service_traits::MD5Sum< ::lab_config::GetRange >
template<>
struct MD5Sum< ::lab_config::GetRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::GetRange >::value();
  }
  static const char* value(const ::lab_config::GetRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::GetRangeResponse> should match
// service_traits::DataType< ::lab_config::GetRange >
template<>
struct DataType< ::lab_config::GetRangeResponse>
{
  static const char* value()
  {
    return DataType< ::lab_config::GetRange >::value();
  }
  static const char* value(const ::lab_config::GetRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_GETRANGE_H
