// Generated by gencpp from file lab_config/StashRangeRequest.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_STASHRANGEREQUEST_H
#define LAB_CONFIG_MESSAGE_STASHRANGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab_config
{
template <class ContainerAllocator>
struct StashRangeRequest_
{
  typedef StashRangeRequest_<ContainerAllocator> Type;

  StashRangeRequest_()
    : color_name()  {
    }
  StashRangeRequest_(const ContainerAllocator& _alloc)
    : color_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_name_type;
  _color_name_type color_name;





  typedef boost::shared_ptr< ::lab_config::StashRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab_config::StashRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StashRangeRequest_

typedef ::lab_config::StashRangeRequest_<std::allocator<void> > StashRangeRequest;

typedef boost::shared_ptr< ::lab_config::StashRangeRequest > StashRangeRequestPtr;
typedef boost::shared_ptr< ::lab_config::StashRangeRequest const> StashRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab_config::StashRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab_config::StashRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab_config::StashRangeRequest_<ContainerAllocator1> & lhs, const ::lab_config::StashRangeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color_name == rhs.color_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab_config::StashRangeRequest_<ContainerAllocator1> & lhs, const ::lab_config::StashRangeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab_config::StashRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab_config::StashRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::StashRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab_config::StashRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::StashRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab_config::StashRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab_config::StashRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1ebd3bdb7f211ac2ddd328c08dba1e4";
  }

  static const char* value(const ::lab_config::StashRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1ebd3bdb7f211acULL;
  static const uint64_t static_value2 = 0x2ddd328c08dba1e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab_config::StashRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab_config/StashRangeRequest";
  }

  static const char* value(const ::lab_config::StashRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab_config::StashRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_name\n"
;
  }

  static const char* value(const ::lab_config::StashRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab_config::StashRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StashRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab_config::StashRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab_config::StashRangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_STASHRANGEREQUEST_H
