// Generated by gencpp from file lab_config/StashRange.msg
// DO NOT EDIT!


#ifndef LAB_CONFIG_MESSAGE_STASHRANGE_H
#define LAB_CONFIG_MESSAGE_STASHRANGE_H

#include <ros/service_traits.h>


#include <lab_config/StashRangeRequest.h>
#include <lab_config/StashRangeResponse.h>


namespace lab_config
{

struct StashRange
{

typedef StashRangeRequest Request;
typedef StashRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StashRange
} // namespace lab_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab_config::StashRange > {
  static const char* value()
  {
    return "b043027b67620a7221fbfd7733360ab7";
  }

  static const char* value(const ::lab_config::StashRange&) { return value(); }
};

template<>
struct DataType< ::lab_config::StashRange > {
  static const char* value()
  {
    return "lab_config/StashRange";
  }

  static const char* value(const ::lab_config::StashRange&) { return value(); }
};


// service_traits::MD5Sum< ::lab_config::StashRangeRequest> should match
// service_traits::MD5Sum< ::lab_config::StashRange >
template<>
struct MD5Sum< ::lab_config::StashRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::StashRange >::value();
  }
  static const char* value(const ::lab_config::StashRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::StashRangeRequest> should match
// service_traits::DataType< ::lab_config::StashRange >
template<>
struct DataType< ::lab_config::StashRangeRequest>
{
  static const char* value()
  {
    return DataType< ::lab_config::StashRange >::value();
  }
  static const char* value(const ::lab_config::StashRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab_config::StashRangeResponse> should match
// service_traits::MD5Sum< ::lab_config::StashRange >
template<>
struct MD5Sum< ::lab_config::StashRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab_config::StashRange >::value();
  }
  static const char* value(const ::lab_config::StashRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab_config::StashRangeResponse> should match
// service_traits::DataType< ::lab_config::StashRange >
template<>
struct DataType< ::lab_config::StashRangeResponse>
{
  static const char* value()
  {
    return DataType< ::lab_config::StashRange >::value();
  }
  static const char* value(const ::lab_config::StashRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB_CONFIG_MESSAGE_STASHRANGE_H
