color_range_list:
  red:
    min: [ 0, 134, 141 ]
    max: [ 255, 255, 166 ]
  green:
    min: [ 23, 0, 136 ]
    max: [ 126, 123, 161 ]
  blue:
    min: [ 0, 0, 0 ]
    max: [ 255, 255, 93 ]
  black:
    min: [ 0, 0, 0 ]
    max: [ 56, 255, 255 ]
  white:
    min: [ 193, 0, 0 ]
    max: [ 255, 255, 255 ]
