color_range_list:
  black:
    max:
    - 80
    - 255
    - 255
    min:
    - 0
    - 0
    - 0
  blue:
    max:
    - 255
    - 255
    - 102
    min:
    - 0
    - 0
    - 0
  goal:
    max:
    - 255
    - 255
    - 255
    min:
    - 0
    - 148
    - 140
  green:
    max:
    - 255
    - 110
    - 255
    min:
    - 0
    - 0
    - 135
  purple:
    max:
    - 110
    - 180
    - 110
    min:
    - 0
    - 60
    - 50
  red:
    max:
    - 255
    - 255
    - 255
    min:
    - 0
    - 153
    - 88
  white:
    max:
    - 255
    - 255
    - 255
    min:
    - 193
    - 0
    - 0
  yellow:
    max:
    - 255
    - 141
    - 255
    min:
    - 0
    - 0
    - 140
