(cl:defpackage puppy_control-srv
  (:use )
  (:export
   "SETRUNACTIONNAME"
   "<SETRUNACTIONNAME-REQUEST>"
   "SETRUNACTIONNAME-REQUEST"
   "<SETRUNACTIONNAME-RESPONSE>"
   "SETRUNACTIONNAME-RESPONSE"
  ))

