# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from puppy_control/Gait.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Gait(genpy.Message):
  _md5sum = "85570b63b58df2eb52f0cdc5f4a30db8"
  _type = "puppy_control/Gait"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 overlap_time
float32 swing_time
float32 clearance_time
float32 z_clearance
"""
  __slots__ = ['overlap_time','swing_time','clearance_time','z_clearance']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       overlap_time,swing_time,clearance_time,z_clearance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Gait, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.overlap_time is None:
        self.overlap_time = 0.
      if self.swing_time is None:
        self.swing_time = 0.
      if self.clearance_time is None:
        self.clearance_time = 0.
      if self.z_clearance is None:
        self.z_clearance = 0.
    else:
      self.overlap_time = 0.
      self.swing_time = 0.
      self.clearance_time = 0.
      self.z_clearance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.overlap_time, _x.swing_time, _x.clearance_time, _x.z_clearance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.overlap_time, _x.swing_time, _x.clearance_time, _x.z_clearance,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.overlap_time, _x.swing_time, _x.clearance_time, _x.z_clearance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.overlap_time, _x.swing_time, _x.clearance_time, _x.z_clearance,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
