# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from puppy_control/Pose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Pose(genpy.Message):
  _md5sum = "baecb41f8598067f3a25cfb12cfeb74d"
  _type = "puppy_control/Pose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 roll
float32 pitch
float32 yaw
float32 height
float32 x_shift
float32 stance_x
float32 stance_y

int32 run_time"""
  __slots__ = ['roll','pitch','yaw','height','x_shift','stance_x','stance_y','run_time']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roll,pitch,yaw,height,x_shift,stance_x,stance_y,run_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Pose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.height is None:
        self.height = 0.
      if self.x_shift is None:
        self.x_shift = 0.
      if self.stance_x is None:
        self.stance_x = 0.
      if self.stance_y is None:
        self.stance_y = 0.
      if self.run_time is None:
        self.run_time = 0
    else:
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.height = 0.
      self.x_shift = 0.
      self.stance_x = 0.
      self.stance_y = 0.
      self.run_time = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7fi().pack(_x.roll, _x.pitch, _x.yaw, _x.height, _x.x_shift, _x.stance_x, _x.stance_y, _x.run_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.roll, _x.pitch, _x.yaw, _x.height, _x.x_shift, _x.stance_x, _x.stance_y, _x.run_time,) = _get_struct_7fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7fi().pack(_x.roll, _x.pitch, _x.yaw, _x.height, _x.x_shift, _x.stance_x, _x.stance_y, _x.run_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.roll, _x.pitch, _x.yaw, _x.height, _x.x_shift, _x.stance_x, _x.stance_y, _x.run_time,) = _get_struct_7fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7fi = None
def _get_struct_7fi():
    global _struct_7fi
    if _struct_7fi is None:
        _struct_7fi = struct.Struct("<7fi")
    return _struct_7fi
