// Generated by gencpp from file puppy_control/SetRunActionNameResponse.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMERESPONSE_H
#define PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puppy_control
{
template <class ContainerAllocator>
struct SetRunActionNameResponse_
{
  typedef SetRunActionNameResponse_<ContainerAllocator> Type;

  SetRunActionNameResponse_()
    : success(false)
    , message()  {
    }
  SetRunActionNameResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRunActionNameResponse_

typedef ::puppy_control::SetRunActionNameResponse_<std::allocator<void> > SetRunActionNameResponse;

typedef boost::shared_ptr< ::puppy_control::SetRunActionNameResponse > SetRunActionNameResponsePtr;
typedef boost::shared_ptr< ::puppy_control::SetRunActionNameResponse const> SetRunActionNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator1> & lhs, const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator1> & lhs, const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puppy_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puppy_control/SetRunActionNameResponse";
  }

  static const char* value(const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRunActionNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puppy_control::SetRunActionNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puppy_control::SetRunActionNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMERESPONSE_H
