// Generated by gencpp from file puppy_control/SetRunActionName.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAME_H
#define PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAME_H

#include <ros/service_traits.h>


#include <puppy_control/SetRunActionNameRequest.h>
#include <puppy_control/SetRunActionNameResponse.h>


namespace puppy_control
{

struct SetRunActionName
{

typedef SetRunActionNameRequest Request;
typedef SetRunActionNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRunActionName
} // namespace puppy_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::puppy_control::SetRunActionName > {
  static const char* value()
  {
    return "b7336d7e4c3e9d0199fd9c319d9a619a";
  }

  static const char* value(const ::puppy_control::SetRunActionName&) { return value(); }
};

template<>
struct DataType< ::puppy_control::SetRunActionName > {
  static const char* value()
  {
    return "puppy_control/SetRunActionName";
  }

  static const char* value(const ::puppy_control::SetRunActionName&) { return value(); }
};


// service_traits::MD5Sum< ::puppy_control::SetRunActionNameRequest> should match
// service_traits::MD5Sum< ::puppy_control::SetRunActionName >
template<>
struct MD5Sum< ::puppy_control::SetRunActionNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetRunActionName >::value();
  }
  static const char* value(const ::puppy_control::SetRunActionNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetRunActionNameRequest> should match
// service_traits::DataType< ::puppy_control::SetRunActionName >
template<>
struct DataType< ::puppy_control::SetRunActionNameRequest>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetRunActionName >::value();
  }
  static const char* value(const ::puppy_control::SetRunActionNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::puppy_control::SetRunActionNameResponse> should match
// service_traits::MD5Sum< ::puppy_control::SetRunActionName >
template<>
struct MD5Sum< ::puppy_control::SetRunActionNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::puppy_control::SetRunActionName >::value();
  }
  static const char* value(const ::puppy_control::SetRunActionNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::puppy_control::SetRunActionNameResponse> should match
// service_traits::DataType< ::puppy_control::SetRunActionName >
template<>
struct DataType< ::puppy_control::SetRunActionNameResponse>
{
  static const char* value()
  {
    return DataType< ::puppy_control::SetRunActionName >::value();
  }
  static const char* value(const ::puppy_control::SetRunActionNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAME_H
