// Generated by gencpp from file puppy_control/SetRunActionNameRequest.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMEREQUEST_H
#define PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puppy_control
{
template <class ContainerAllocator>
struct SetRunActionNameRequest_
{
  typedef SetRunActionNameRequest_<ContainerAllocator> Type;

  SetRunActionNameRequest_()
    : name()
    , wait(false)  {
    }
  SetRunActionNameRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , wait(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _wait_type;
  _wait_type wait;





  typedef boost::shared_ptr< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRunActionNameRequest_

typedef ::puppy_control::SetRunActionNameRequest_<std::allocator<void> > SetRunActionNameRequest;

typedef boost::shared_ptr< ::puppy_control::SetRunActionNameRequest > SetRunActionNameRequestPtr;
typedef boost::shared_ptr< ::puppy_control::SetRunActionNameRequest const> SetRunActionNameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator1> & lhs, const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.wait == rhs.wait;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator1> & lhs, const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puppy_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bdb05678ab291aa820711162205b0ef";
  }

  static const char* value(const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bdb05678ab291aaULL;
  static const uint64_t static_value2 = 0x820711162205b0efULL;
};

template<class ContainerAllocator>
struct DataType< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puppy_control/SetRunActionNameRequest";
  }

  static const char* value(const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"bool wait\n"
;
  }

  static const char* value(const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.wait);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRunActionNameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puppy_control::SetRunActionNameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puppy_control::SetRunActionNameRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_SETRUNACTIONNAMEREQUEST_H
