// Generated by gencpp from file puppy_control/Velocity.msg
// DO NOT EDIT!


#ifndef PUPPY_CONTROL_MESSAGE_VELOCITY_H
#define PUPPY_CONTROL_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puppy_control
{
template <class ContainerAllocator>
struct Velocity_
{
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
    : x(0.0)
    , y(0.0)
    , yaw_rate(0.0)  {
    }
  Velocity_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::puppy_control::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puppy_control::Velocity_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity_

typedef ::puppy_control::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::puppy_control::Velocity > VelocityPtr;
typedef boost::shared_ptr< ::puppy_control::Velocity const> VelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puppy_control::Velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puppy_control::Velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puppy_control::Velocity_<ContainerAllocator1> & lhs, const ::puppy_control::Velocity_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puppy_control::Velocity_<ContainerAllocator1> & lhs, const ::puppy_control::Velocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puppy_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::puppy_control::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puppy_control::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puppy_control::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::Velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puppy_control::Velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puppy_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad70c6ce8f1b0a052968829ccde7f72d";
  }

  static const char* value(const ::puppy_control::Velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad70c6ce8f1b0a05ULL;
  static const uint64_t static_value2 = 0x2968829ccde7f72dULL;
};

template<class ContainerAllocator>
struct DataType< ::puppy_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puppy_control/Velocity";
  }

  static const char* value(const ::puppy_control::Velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puppy_control::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw_rate\n"
;
  }

  static const char* value(const ::puppy_control::Velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puppy_control::Velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puppy_control::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puppy_control::Velocity_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUPPY_CONTROL_MESSAGE_VELOCITY_H
